### ISSUE TITLE
Model.do_iterate calls put_on_request incorrectly

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/perl-Bivio#64]
It is passing "self" which gets interpreted as a boolean durable.

**Comment by schellj** [comment]
The incorrect `put_on_request` call can certainly be fixed, but I was looking into this and it doesn't look like there is actually a deleterious effect because `PropertyModel->iterate_next_and_load` deletes the model from the request after the last row.

https://github.com/biviosoftware/perl-Bivio/blob/master/Biz/PropertyModel.pm#L346
https://github.com/biviosoftware/perl-Bivio/blob/master/Biz/PropertyModel.pm#L938
